import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { format } from 'date-fns';
import { ru } from 'date-fns/locale';
import { enUS } from 'date-fns/locale';
import i18n from '@shared/i18n';
import type {
  Pet,
  GlucoseReading,
  InjectionLog,
  SymptomEntry,
  MealRelation,
  SymptomType,
  SymptomSeverity,
} from '@storage/domain/types';

const ACCENT = '#4F8EF7';
const ACCENT_LIGHT = '#E8F0FE';
const TEXT = '#1C1C1E';
const TEXT_SEC = '#6D6D72';
const BORDER = '#E5E5EA';
const BG = '#F8F9FA';

function isRu(): boolean {
  return i18n.language?.startsWith('ru') ?? true;
}

function getDateLocale() {
  return isRu() ? ru : enUS;
}

interface Labels {
  mealLabels: Record<MealRelation, string>;
  symptomLabels: Record<SymptomType, string>;
  severityLabels: Record<SymptomSeverity, string>;
  title: string;
  subtitle: string;
  labelName: string;
  labelBreed: string;
  labelDiagnosisDate: string;
  labelDiabetesType: string;
  labelInsulin: string;
  diabetesType1: string;
  diabetesType2: string;
  diabetesTypeUnknown: string;
  sectionGlucose: (count: number) => string;
  sectionInjections: string;
  sectionSymptoms: (count: number) => string;
  colDateTime: string;
  colMmol: string;
  colMgdl: string;
  colMeal: string;
  colNotes: string;
  colDose: string;
  colInsulinType: string;
  colSymptoms: string;
  colSeverity: string;
  emptyGlucose: string;
  emptyInjections: string;
  emptySymptoms: string;
  footer: string;
  doseUnit: string;
  dialogTitle: string;
}

function getLabels(): Labels {
  if (isRu()) {
    return {
      mealLabels: {
        before_meal: 'До еды',
        after_meal: 'После еды',
        fasting: 'Натощак',
        unspecified: '—',
      },
      symptomLabels: {
        hindLimbWeakness: 'Слабость задних лап',
        weightLoss: 'Потеря веса',
        polyuria: 'Полиурия',
        polydipsia: 'Полидипсия',
        lossOfAppetite: 'Потеря аппетита',
        behavioralChanges: 'Поведенческие изменения',
        lethargy: 'Вялость',
        vomiting: 'Рвота',
        diarrhea: 'Диарея',
        other: 'Другое',
      },
      severityLabels: {
        mild: 'Лёгкая',
        moderate: 'Умеренная',
        severe: 'Тяжёлая',
      },
      title: 'DiaPet \u2014 Медицинский отчёт',
      subtitle: 'Дневник диабета для ветеринара',
      labelName: 'Имя',
      labelBreed: 'Порода',
      labelDiagnosisDate: 'Дата диагноза',
      labelDiabetesType: 'Тип диабета',
      labelInsulin: 'Инсулин',
      diabetesType1: 'Тип 1',
      diabetesType2: 'Тип 2',
      diabetesTypeUnknown: 'Неизвестен',
      sectionGlucose: (count) => `Показания глюкозы (${count} записей)`,
      sectionInjections: 'Последние инъекции (до 10)',
      sectionSymptoms: (count) => `Симптомы (${count} записей)`,
      colDateTime: 'Дата / время',
      colMmol: 'ммоль/л',
      colMgdl: 'мг/дл',
      colMeal: 'Приём пищи',
      colNotes: 'Заметки',
      colDose: 'Доза',
      colInsulinType: 'Тип инсулина',
      colSymptoms: 'Симптомы',
      colSeverity: 'Тяжесть',
      emptyGlucose: 'Нет данных за выбранный период',
      emptyInjections: 'Нет данных об инъекциях',
      emptySymptoms: 'Нет записей о симптомах',
      footer: 'Сгенерировано в DiaPet',
      doseUnit: 'ед.',
      dialogTitle: 'DiaPet \u2014 Медицинский отчёт',
    };
  }

  return {
    mealLabels: {
      before_meal: 'Before meal',
      after_meal: 'After meal',
      fasting: 'Fasting',
      unspecified: '\u2014',
    },
    symptomLabels: {
      hindLimbWeakness: 'Hind limb weakness',
      weightLoss: 'Weight loss',
      polyuria: 'Polyuria',
      polydipsia: 'Polydipsia',
      lossOfAppetite: 'Loss of appetite',
      behavioralChanges: 'Behavioral changes',
      lethargy: 'Lethargy',
      vomiting: 'Vomiting',
      diarrhea: 'Diarrhea',
      other: 'Other',
    },
    severityLabels: {
      mild: 'Mild',
      moderate: 'Moderate',
      severe: 'Severe',
    },
    title: 'DiaPet \u2014 Medical Report',
    subtitle: 'Diabetes diary for veterinarian',
    labelName: 'Name',
    labelBreed: 'Breed',
    labelDiagnosisDate: 'Diagnosis date',
    labelDiabetesType: 'Diabetes type',
    labelInsulin: 'Insulin',
    diabetesType1: 'Type 1',
    diabetesType2: 'Type 2',
    diabetesTypeUnknown: 'Unknown',
    sectionGlucose: (count) => `Glucose readings (${count} records)`,
    sectionInjections: 'Recent injections (up to 10)',
    sectionSymptoms: (count) => `Symptoms (${count} records)`,
    colDateTime: 'Date / time',
    colMmol: 'mmol/L',
    colMgdl: 'mg/dL',
    colMeal: 'Meal relation',
    colNotes: 'Notes',
    colDose: 'Dose',
    colInsulinType: 'Insulin type',
    colSymptoms: 'Symptoms',
    colSeverity: 'Severity',
    emptyGlucose: 'No data for selected period',
    emptyInjections: 'No injection records',
    emptySymptoms: 'No symptom records',
    footer: 'Generated by DiaPet',
    doseUnit: 'u.',
    dialogTitle: 'DiaPet \u2014 Medical Report',
  };
}

function formatDate(iso: string): string {
  try {
    return format(new Date(iso), 'dd.MM.yyyy HH:mm', { locale: getDateLocale() });
  } catch {
    return iso;
  }
}

function formatDateShort(iso: string | undefined): string {
  if (!iso) return '\u2014';
  try {
    return format(new Date(iso), 'dd.MM.yyyy', { locale: getDateLocale() });
  } catch {
    return iso;
  }
}

function buildHtml(
  pet: Pet,
  glucoseReadings: GlucoseReading[],
  injections: InjectionLog[],
  symptoms: SymptomEntry[],
): string {
  const L = getLabels();
  const lang = isRu() ? 'ru' : 'en';
  const now = format(new Date(), 'dd MMMM yyyy, HH:mm', { locale: getDateLocale() });

  const diabetesTypeLabel =
    pet.diabetesType === 'type1'
      ? L.diabetesType1
      : pet.diabetesType === 'type2'
        ? L.diabetesType2
        : L.diabetesTypeUnknown;

  // Glucose table rows
  const glucoseRows = glucoseReadings
    .slice(0, 100)
    .map(
      (r) => `
      <tr>
        <td>${formatDate(r.recordedAt)}</td>
        <td><strong>${r.valueMmol.toFixed(1)}</strong></td>
        <td>${r.valueMgdl}</td>
        <td>${L.mealLabels[r.mealRelation]}</td>
        <td>${r.notes ?? ''}</td>
      </tr>`,
    )
    .join('');

  // Injection table rows (last 10)
  const injectionRows = injections
    .slice(0, 10)
    .map(
      (inj) => `
      <tr>
        <td>${formatDate(inj.administeredAt)}</td>
        <td>${inj.doseUnits} ${L.doseUnit}</td>
        <td>${inj.insulinType}</td>
        <td>${inj.notes ?? ''}</td>
      </tr>`,
    )
    .join('');

  // Symptom rows
  const symptomRows = symptoms
    .slice(0, 50)
    .map(
      (s) => `
      <tr>
        <td>${formatDate(s.recordedAt)}</td>
        <td>${s.symptomTypes.map((t) => L.symptomLabels[t] ?? t).join(', ')}</td>
        <td>${L.severityLabels[s.severity]}</td>
        <td>${s.notes ?? ''}</td>
      </tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif;
      color: ${TEXT};
      background: #fff;
      font-size: 12px;
      line-height: 1.5;
      padding: 32px;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid ${ACCENT};
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    .header h1 {
      font-size: 22px;
      color: ${ACCENT};
      margin-bottom: 4px;
    }
    .header .subtitle {
      font-size: 14px;
      color: ${TEXT_SEC};
    }
    .pet-info {
      display: flex;
      justify-content: space-between;
      background: ${ACCENT_LIGHT};
      border-radius: 8px;
      padding: 12px 16px;
      margin-bottom: 24px;
    }
    .pet-info .col {
      flex: 1;
    }
    .pet-info .label {
      font-size: 10px;
      color: ${TEXT_SEC};
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .pet-info .value {
      font-size: 13px;
      font-weight: 600;
    }
    .section {
      margin-bottom: 24px;
    }
    .section h2 {
      font-size: 15px;
      color: ${ACCENT};
      border-bottom: 1px solid ${BORDER};
      padding-bottom: 6px;
      margin-bottom: 10px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 11px;
    }
    th {
      background: ${BG};
      color: ${TEXT_SEC};
      font-weight: 600;
      text-align: left;
      padding: 8px 6px;
      border-bottom: 2px solid ${BORDER};
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 0.3px;
    }
    td {
      padding: 6px;
      border-bottom: 1px solid ${BORDER};
      vertical-align: top;
    }
    tr:nth-child(even) td {
      background: ${BG};
    }
    .empty {
      color: ${TEXT_SEC};
      font-style: italic;
      padding: 12px 0;
    }
    .footer {
      margin-top: 32px;
      padding-top: 12px;
      border-top: 1px solid ${BORDER};
      text-align: center;
      font-size: 10px;
      color: ${TEXT_SEC};
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${L.title}</h1>
    <div class="subtitle">${L.subtitle}</div>
  </div>

  <div class="pet-info">
    <div class="col">
      <div class="label">${L.labelName}</div>
      <div class="value">${pet.name}</div>
    </div>
    <div class="col">
      <div class="label">${L.labelBreed}</div>
      <div class="value">${pet.breed ?? '\u2014'}</div>
    </div>
    <div class="col">
      <div class="label">${L.labelDiagnosisDate}</div>
      <div class="value">${formatDateShort(pet.diagnosisDate)}</div>
    </div>
    <div class="col">
      <div class="label">${L.labelDiabetesType}</div>
      <div class="value">${diabetesTypeLabel}</div>
    </div>
    <div class="col">
      <div class="label">${L.labelInsulin}</div>
      <div class="value">${pet.insulinType ?? '\u2014'}</div>
    </div>
  </div>

  <div class="section">
    <h2>${L.sectionGlucose(glucoseReadings.length)}</h2>
    ${
      glucoseReadings.length > 0
        ? `<table>
        <thead>
          <tr>
            <th>${L.colDateTime}</th>
            <th>${L.colMmol}</th>
            <th>${L.colMgdl}</th>
            <th>${L.colMeal}</th>
            <th>${L.colNotes}</th>
          </tr>
        </thead>
        <tbody>${glucoseRows}</tbody>
      </table>`
        : `<p class="empty">${L.emptyGlucose}</p>`
    }
  </div>

  <div class="section">
    <h2>${L.sectionInjections}</h2>
    ${
      injections.length > 0
        ? `<table>
        <thead>
          <tr>
            <th>${L.colDateTime}</th>
            <th>${L.colDose}</th>
            <th>${L.colInsulinType}</th>
            <th>${L.colNotes}</th>
          </tr>
        </thead>
        <tbody>${injectionRows}</tbody>
      </table>`
        : `<p class="empty">${L.emptyInjections}</p>`
    }
  </div>

  <div class="section">
    <h2>${L.sectionSymptoms(symptoms.length)}</h2>
    ${
      symptoms.length > 0
        ? `<table>
        <thead>
          <tr>
            <th>${L.colDateTime}</th>
            <th>${L.colSymptoms}</th>
            <th>${L.colSeverity}</th>
            <th>${L.colNotes}</th>
          </tr>
        </thead>
        <tbody>${symptomRows}</tbody>
      </table>`
        : `<p class="empty">${L.emptySymptoms}</p>`
    }
  </div>

  <div class="footer">
    ${L.footer} &bull; ${now}
  </div>
</body>
</html>`;
}

export interface VetReportData {
  pet: Pet;
  glucoseReadings: GlucoseReading[];
  injections: InjectionLog[];
  symptoms: SymptomEntry[];
}

export async function generateVetReportPdf(data: VetReportData): Promise<void> {
  const html = buildHtml(
    data.pet,
    data.glucoseReadings,
    data.injections,
    data.symptoms,
  );

  const { uri } = await Print.printToFileAsync({ html });

  const L = getLabels();
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: L.dialogTitle,
    UTI: 'com.adobe.pdf',
  });
}
